const routes = require('next-routes')

module.exports = routes()
    // .add('homepage', '/', '')
    .add('countdown', '/','countdown')
    .add('preRegistration', '/pre-registration','preRegistration')
    .add('login', '/login','login')    
    .add('registration', '/registration','registration')    
    .add('liveChat', '/live-chat','liveChat')    
    .add('mainHall', '/main-hall','mainHall')    
    .add('booth', '/booth','booth')    
    .add('boothVideo', '/booth-video','boothVideo')    
    .add('boothMomobil', '/booth-momobil','boothMomobil')    
    .add('boothMomotor', '/booth-momotor','boothMomotor')    
    .add('pageInformation', '/information','pageInformation')    
    .add('sobatFirst', '/sobat-1','sobatFirst')    
    .add('sobatSecond', '/sobat-2','sobatSecond')    
    .add('sobatThird', '/sobat-3','sobatThird')    
    .add('boothTypeOne', '/booth/booth-1/:id','boothTypeOne')    
    .add('boothTypeThree', '/booth/booth-3/:id','boothTypeThree')    
