const routes = require('next-routes')

module.exports = routes()
    // .add('homepage', '/', '')
    .add('countdown', '/','countdown')
    .add('preRegistration', '/pre-registration','preRegistration')
    .add('login', '/login','login')    
    .add('registration', '/registration','registration')    
    .add('liveChat', '/live-chat','liveChat')    
    .add('mainHall', '/main-hall','mainHall')    
    .add('booth', '/booth','booth')    
    .add('boothVideo', '/booth-video','boothVideo')    
    .add('boothMomobil', '/booth-momobil','boothMomobil')    
    .add('boothMomotor', '/booth-momotor','boothMomotor')    
    .add('pageInformation', '/information','pageInformation')    
